language: rust
rust:
        - stable
        - beta
        - nightly
matrix:
        allow_failures:
                - rust: beta
cache: cargo
script:
        - cargo build --verbose --all
        - cargo build --verbose --all --features slow_impl
        - cargo build --verbose --all --features parallel
